apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: pusher
    image: dysproz/devops-sig-pusher
    volumeMounts:
      - name: shared
        mountPath: /etc/config
  - name: http-serve
    image: dysproz/devops-sig-http
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: shared
        mountPath: /etc/config
  volumes:
    - name: shared
      emptyDir: {}
  restartPolicy: Never

